### ISSUE TITLE
[vicious.widgets.mpd] Only the last artist is being returned in "{Artist}".

### ISSUE THREAD

**Issue by toniz4** [vicious-widgets/vicious#116]
First of all, thanks for maintaining this library.

Currently, when mpd reports that a song has more than 1 artist, only the last one goes to `{Artist}`.

This is what mpd returns for example:

```
OK MPD 0.23.5
ACK [3@0] {password} incorrect password
volume: 100
repeat: 0
random: 0
single: 0
consume: 0
partition: default
playlist: 24
playlistlength: 21
mixrampdb: 0
state: play
song: 15
songid: 27
time: 97:127
elapsed: 97.053
bitrate: 946
duration: 127.120
audio: 44100:16:2
nextsong: 16
nextsongid: 28
OK
file: ceo@business.net - incentivize unpaid overtime/05 - rewind.flac
Last-Modified: 2023-02-19T21:45:50Z
Format: 44100:16:2
Title: rewind
Artist: ceo@business.net
Artist: lentra
Album: incentivize unpaid overtime
AlbumArtist: ceo@business.net
AlbumArtist: lentra
Track: 5
Disc: 1
Genre: Rap/Hip Hop
Date: 2020-02-21
Time: 127
duration: 127.120
Pos: 15
Id: 27
OK
```

What I propose is adding a `"{Artists}"`, that will store all artists separated with a coma (or with a configurable separator). That way it will not break how "{Artist}" behave currently.

If you are ok with this feature I can (try to) implement it.

Thanks!

**Comment by toniz4** [comment]
it's a flac file, it uses the vorbis format for tags.

https://www.xiph.org/vorbis/doc/v-comment.html

In the field names section you can see that it's possible to have one or more names.

-------- Original Message --------

**Comment by McSinyx** [comment]
I see.  Does mpd output any defined tag or just part of a subset?  Not that it matters since the widget hardcodes it anyway.

If you're to submit a patch, generalize it for all tags, since something like genre could also have multiple values.  Joined string with a configurable separator sounds fine and probably work best with `vicious.register`, e.g. `format` would have to be a function if the value were an array.
