### ISSUE TITLE
mem widget reporting wrong value

### ISSUE THREAD

**Issue by gulafaran** [vicious-widgets/vicious#84]
this commit https://github.com/vicious-widgets/vicious/commit/0db5f3f2221ecff3a425fe33990eac0abf180f79#diff-9a1b8eda59a5fb3cb53edd08753fbd91 broke the reported value of  "Memory usage in MiB"

it claims im using over 6GB at boot, and reverting that commit im back at normal sane values which "free -h" reports too.

**Comment by McSinyx** [comment]
Take a look at #59 and [its linked kernel commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773):

> Many load balancing and workload placing programs check /proc/meminfo to
> estimate how much free memory is available.  They generally do this by
> adding up "free" and "cached", which was fine ten years ago, but is
> pretty much guaranteed to be wrong today.
>
> It is wrong because Cached includes memory that is not freeable as page
> cache, for example shared memory segments, tmpfs, and ramfs, and it does
> not include reclaimable slab memory, which can take up a large fraction
> of system memory on mostly idle systems with lots of files.

to figure out if you really want `MemTotal - MemFree - Buffers - Cached` or `MemTotal - MemAvailable`. I'd also love to see your `/proc/meminfo` to investigate further.

**Comment by gulafaran** [comment]
yeah hm weird, however here is free -h

[tom@tom-pc ~]$ free -h
                  total        used        free      shared  buff/cache   available
Mem:         15Gi       2.0Gi        11Gi       100Mi       1.7Gi        10Gi
Swap:         2.0Gi          0B       2.0Gi

and /proc/meminfo https://gist.github.com/gulafaran/638c5ac8efbcbba7b616d669a4963b18

so if i calculate this right it means.
MemTotal - MemFree - Buffers - Cached
16375596 - 12515232 - 65768 - 1671596 = 2123000 , which corresponds to free -m

but
MemTotal - MemAvailable
16375596 - 10788976 = 5586620

so something odd is going on here.

**Comment by McSinyx** [comment]
Looking at [this diff (I assume that left is after a while of use, right is newly booted, due to buffers)](https://gist.github.com/McSinyx/f04c0224800eac33e62bcfac8bb47bbb/revisions?diff=split), I spot that MemAvailable seems to go up after a while. From the kernel commit, you can see that available is roughly the maximum of `free + page_cache/2 - low_watermark` and `free + page_cache - low_watermark*2`. Not a kernel expert, so I don't know how that got magically decreased, as cache rose and watermark should oscillate around a same value. Digging into `/proc/zoneinfo` for total low watermark might help (`grep low /proc/zoneinfo`).

Note that `free` is implemented to calculate `used = total - free - buffer - cache` so of course these numbers match. What I wonder is if which figure would be more meaning full: amount of RAM ready to be used (available) or amount that can be used (free + buffer + cache) (not exactly if you read the kernel commit I linked above).

**Comment by gulafaran** [comment]
ok actually you are right, the more meaning full figure is as you say and have changed to, after some digging i found that i had still had around the vm.min_free_kbytes = 1677721 i put there for testing the oom reaper/swapping deadlocks... yeah it reports as it should after removing that heh.

**Comment by McSinyx** [comment]
I'm glad we found out the root of the problem. Please close the issue if you think it's solved. BTW it's funny that both of us non-native English speaker used the *bon apple tea* ***meaning full*** without even noticing it :smile:
